const express = require('express');
const router = express.Router();
const authController = require('../controllers/auth');
const { validate } = require('../util/validate');
const {signUpSchema,loginSchema,updateSchema} = require('../validations/authSchema');
const isAuth = require('../middlewares/is-auth');
router.post('/signup',validate(signUpSchema),authController.signup);
router.post('/login',validate(loginSchema),authController.login);
router.get('/profile',isAuth,authController.profile);
router.patch('/profile',isAuth,validate(updateSchema),authController.updateProfile);
module.exports = router;